// Generated by CoffeeScript 1.6.2
(function() {
  var capitalize, extend, series, toUnderscore;

  extend = function(source, object) {
    var prop;

    for (prop in object) {
      if (object.hasOwnProperty(prop)) {
        source[prop] = object[prop];
      }
    }
    return source;
  };

  series = function(binding, callbacks, last) {
    var next;

    next = function() {
      var callback;

      callback = callbacks.shift();
      if (callback) {
        return callback.func.call(binding, function() {
          if (arguments[0]) {
            throw new Error(arguments[0]);
          }
          binding[callback.field] = arguments[1];
          return next();
        });
      } else {
        return last();
      }
    };
    return next();
  };

  capitalize = function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };

  toUnderscore = function(string) {
    return string.replace(/([A-Z])/g, function($1) {
      return "_" + $1.toLowerCase();
    });
  };

  exports.extend = extend;

  exports.series = series;

  exports.capitalize = capitalize;

  exports.toUnderscore = toUnderscore;

}).call(this);
